HEADER = 64

# RECEIVED = 'MSG RECEIVED'
REQUEST_BLOCKCHAIN = 'REQUESTING_MAIN_BLOCKCHAIN'
REQUEST_BLOCK = 'REQUESTING_BLOCK'
REQUEST_TX = 'REQUESTING_TRANSACTION'
PING_CALL = 'PING_CALL'
PING_RESPONSE = 'PING_RESPONSE'